### ISSUE TITLE
(website) Feedback navigation button broken

### ISSUE THREAD

**Issue by jaymakes11** [ihucos/counter.dev#81] opened 2022-09-08 23:33 UTC
When clicking it a new tab opens with the URL "about:blank" and that's it. 

I'm using Brave. Lowered the shields but problem persists.

**Comment by jaymakes11** [comment] 2022-09-08 23:34
btw: love what you're doing with this. love that fact that Redis is the primary data store (as I understand, is this correct?).

**Comment by ihucos** [comment] 2022-09-14 18:34
Thanks for the issue. Hmm, I am unable to reproduce. On which page is the feedback button you clicked. When you hover the button, does it say "mailto:mail@irae.me"?

>  love that fact that Redis is the primary data store (as I understand, is this correct?).

Yes, sir. Redis is the primary database. I am working on regularly saving the redis data to sql (Kind of similiar to a "data warehouse" model). I did write a blog post on my current employers blog that gives some insight into that: https://engineering.getbyrd.com/should-redis-be-used-as-a-primary-database Generally it works.

**Comment by ihucos** [comment] 2022-09-19 10:15
Can't reproduce, closing. Feel free to reopen with the exact link location.

**Closed by ihucos** 2022-09-19 10:15 UTC
