### ISSUE TITLE
Script and DNS Error

### ISSUE THREAD

**Issue by birobirobiro** [ihucos/counter.dev#123] opened 2023-10-02 14:31 UTC
This site can’t be reached

![image](https://github.com/ihucos/counter.dev/assets/22185823/93fc2fe0-8196-4650-bf88-d94a10ee91dc)

GET https://cdn.counter.dev/script.js net::ERR_NAME_NOT_RESOLVED

![image](https://github.com/ihucos/counter.dev/assets/22185823/df948102-dcbc-4fc3-b7e4-63acd18a2bf6)

**Comment by birobirobiro** [comment] 2023-10-02 14:56
> Ah I wonder if that's why the site is inaccessible?

Probably

**Comment by saif71** [comment] 2023-10-03 11:52
Okay the domain expired... -_- 😁😑😑 

![image](https://github.com/ihucos/counter.dev/assets/6561498/541723a5-b680-44b7-9a98-c3b37e6e7897)

**Comment by birobirobiro** [comment] 2023-10-03 11:54
I'm using this alternative for now, it's also free and very complete: 

https://umami.is/

**Comment by DanHakimi** [comment] 2023-10-03 14:53
[They're just waiting for DNS migration](https://twitter.com/DevCounter/status/1709212441328951694). Should be working again soon!

**Comment by ihucos** [comment] 2023-10-03 18:37
duplicate of https://github.com/ihucos/counter.dev/issues/124

In any case hat is obviously a mistake from my part.

**Closed by ihucos** 2023-10-03 18:37 UTC
